services:
  mlflow:
    image: python:3.11-slim
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlartifacts:/app/mlartifacts
    working_dir: /app
    command: >
      sh -c "
        pip install mlflow==3.3.2 &&
        mlflow ui --host 0.0.0.0 --port 5000
      "

  model-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    restart: unless-stopped

 